# Generated by Django 5.0.6 on 2024-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
