# Generated by Django 5.0.6 on 2024-10-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='id_number',
            field=models.CharField(default='default_id', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='default_id', max_length=20),
        ),
    ]
