# Generated by Django 5.0.6 on 2025-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('homework', 'Homework'), ('project', 'Project'), ('exam', 'Exam')], default='assignment', max_length=20),
        ),
    ]
