# Generated by Django 5.0.6 on 2025-04-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_assignment_assignment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_majors', to='registration.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_courses', to='registration.major')),
            ],
            options={
                'unique_together': {('major', 'course')},
            },
        ),
    ]
