# Generated by Django 5.0.6 on 2025-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_assignment_is_closed_assignment_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='extra_time_period',
            field=models.IntegerField(default=0, help_text='Extra time (in days) for late submissions. Set to 0 for no extra time, or -1 for unlimited time.'),
        ),
    ]
