# Generated by Django 5.0.6 on 2025-03-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_module_announcement_module_assignment_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
