# Generated by Django 5.0.6 on 2025-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_assignment_extra_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='extra_time_period',
            field=models.IntegerField(default=2, help_text='Extra time (in days) for late submissions. Set to 0 for no extra time, or -1 for unlimited time.'),
        ),
    ]
