# Generated by Django 5.0.6 on 2025-03-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_module_announcement_module_assignment_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_modules', to='registration.module'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_modules', to='registration.module'),
        ),
    ]
