# Generated by Django 5.0.6 on 2024-07-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_enrollment_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='professor',
        ),
    ]
