# Generated by Django 5.0.6 on 2024-10-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
