# Generated by Django 5.0.6 on 2025-03-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_assignment_extra_time_period_and_more'),
        ('registration', '0005_grade'),
    ]

    operations = [
    ]
