# Generated by Django 5.0.6 on 2025-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_merge_20250316_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major_id',
            field=models.IntegerField(default=0),
        ),
    ]
