# Generated by Django 5.0.6 on 2025-03-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_course_major_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='major_id',
            field=models.IntegerField(default='0'),
        ),
    ]
