# Generated by Django 5.0.6 on 2025-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_course_major_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='major_id',
            field=models.IntegerField(default=0),
        ),
    ]
