# Generated by Django 5.0.6 on 2025-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_course_major_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='major_id',
        ),
        migrations.AddField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(related_name='courses', to='registration.major'),
        ),
    ]
