# Generated by Django 5.0.6 on 2024-09-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='ui_preset',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
